### ISSUE TITLE
what is "HF_MuBERT_base_MPD-10Kh-MusicAll-900h-fma-full-noshit_HPO-v4_crop5s_ECD-v8_mix-v3-0.5_ckpt_136_250000" ?

### ISSUE THREAD

**Issue by 0417keito** [a43992899/MARBLE-Benchmark#2]
I get the following error when I run "python . extract -c configs/mert/MERT-v1-95M/EMO.yaml", I get the following error What is this "HF_MuBERT_base_MPD-10Kh-MusicAll-900h-fma-full-noshit_HPO-v4_crop5s_ECD-v8_mix-v3-0.5_ckpt_136_250000"?

`Found 0 audio files
Loading HuBERT model from data/hubert_data/HF_MuBERT_base_MPD-10Kh-MusicAll-900h-fma-full-noshit_HPO-v4_crop5s_ECD-v8_mix-v3-0.5_ckpt_136_250000
Traceback (most recent call last):
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'data/hubert_data/HF_MuBERT_base_MPD-10Kh-MusicAll-900h-fma-full-noshit_HPO-v4_crop5s_ECD-v8_mix-v3-0.5_ckpt_136_250000'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/usr/MARBLE-Benchmark/./__main__.py", line 89, in <module>
    args.main_func(args)
  File "/home/usr/MARBLE-Benchmark/./benchmark/extract.py", line 27, in main
    extract_main(config)
  File "/home/usr/MARBLE-Benchmark/./benchmark/models/musichubert_hf/extract_bert_features.py", line 57, in main
    feature_extractor = FeatureExtractor(
  File "/home/usr/MARBLE-Benchmark/./benchmark/models/musichubert_hf/hf_pretrains.py", line 148, in __init__
    self.model = MusicHubertModel.from_pretrained(pre_trained_folder)
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2305, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/usr/miniconda/envs/test_env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 650, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'data/hubert_data/HF_MuBERT_base_MPD-10Kh-MusicAll-900h-fma-full-noshit_HPO-v4_crop5s_ECD-v8_mix-v3-0.5_ckpt_136_250000'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'data/hubert_data/HF_MuBERT_base_MPD-10Kh-MusicAll-900h-fma-full-noshit_HPO-v4_crop5s_ECD-v8_mix-v3-0.5_ckpt_136_250000' is the correct path to a directory containing a config.json file`

**Comment by a43992899** [comment]
Sorry for the internal local file naming, the configs of MERT have been updated, you should be able to automatically load from huggingface.

**Comment by 0417keito** [comment]
thanks!
